services:
  php:
    build: ./php
    volumes:
      - ./speakout:/var/www/html
    depends_on:
      - db
    restart: always

  webserver:
    image: nginx:latest
    ports:
      - "8081:80"
    volumes:
      - ./speakout:/var/www/html
      - ./php/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    restart: always

  db:
    image: mariadb:latest
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: dbspeakout
      MYSQL_USER: speakoutuser
      MYSQL_PASSWORD: speakoutpass
    volumes:
      - db_data:/var/lib/mysql
      - ./db/dbspeakout_officiall.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8082:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: rootpass
    restart: always

volumes:
  db_data:
